name: Deploy to HF Space
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: Check large files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 10485760
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            hf_space
            policy_rag
          sparse-checkout-cone-mode: false
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://lw2134:$HF_TOKEN@huggingface.co/spaces/lw2134/policy_rag main
