name: Deploy to Huggingface Spaces
on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      # Initialize a bare repository to configure sparse-checkout before fetching any files
      - name: Initialize Git repository
        run: |
          git init
          git branch -m main
          git config user.email "ledger.west@gmail.com"
          git config user.name "Ledger"
          git remote add origin https://github.com/${{ github.repository }}
          git config core.sparseCheckout true

      # Configure sparse checkout to include only the desired directories
      - name: Setup sparse checkout
        run: |
          echo "hf_space/*" >> .git/info/sparse-checkout
          echo "policy_rag/*" >> .git/info/sparse-checkout
          git pull --depth 1 origin main

      # Step to remove everything except the required directories
      - name: Clean up repo to keep only necessary files
        run: |
          find . -mindepth 1 ! -regex '^./hf_space\(/.*\)?' ! -regex '^./policy_rag\(/.*\)?' -delete

      # Step to move the contents of hf_space/ to the root
      - name: Move hf_space contents to root level
        run: |
          mv hf_space/* .
          rm -rf hf_space

      # Step to force push the selected directories to Hugging Face Spaces
      - name: Force push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git add --sparse .
          git commit -m "Sync hf_space contents to root and push policy_rag"
          git push https://lw2134:$HF_TOKEN@huggingface.co/spaces/lw2134/policy-rag-space main --force